### ISSUE TITLE
Create Python package structure and release to PyPI

### ISSUE THREAD

**Issue by john-sandall** [john-sandall/maven#1]
# Tasks
- [x] [#2: Run through Python packaging to create installable package](2).
- [x] Decide on a license.
- [x] Push Maven to PyPI as a 0.0.1 release.
- [x] Add a minimally useful pipeline.
