### ISSUE TITLE
0.1 release

### ISSUE THREAD

**Issue by john-sandall** [john-sandall/maven#5]
Focus for 0.1 is to get it to a releasable state where I'm not entirely ashamed of how basic it all is. Task priority is on the [Core Projects board](https://github.com/john-sandall/maven/projects/1).

# Tasks
**Core**
- [x] #3 is done and [0.0.3 is live](https://pypi.org/project/maven/)!
- [x] #9: Add some tests
- [x] #10: Add [test info to setup.py](https://python-packaging.readthedocs.io/en/latest/testing.html)

**Pipeline design**
- [x] Add dataset caching ([design inspiration](https://github.com/RaRe-Technologies/gensim-data))

**New pipelines**
- [x] #19: Clean up 2015 results to use HoC data
- [x] #20: Add in 2017 UK/GB election results data
- [x] #21: Fix up UK2015Model to work with updated HoC data
- [x] #22: Create UK2017Model
- [x] #29: Update polling data using Mark Pack's PollBase
- [x] Add in [this notebook](https://github.com/six50/hackathon/blob/master/model/SixFifty%20GE2017%20-%201%20-%20Create%20Model%20Dataset.ipynb) in order to make it easy to get to a model ready dataset.

**Comment by john-sandall** [comment]
This is now released: https://github.com/john-sandall/maven/releases/tag/v0.1.0
