### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by john-sandall** [john-sandall/maven#8]
Focus for 0.2 will be to bring in some more Python best practices. Feeling quite inspired after catching up with [Cheuk](https://github.com/Cheukting/picknmix), there's a lot of things going on in picknmix that are really nice.

# Tasks
- [ ] Use [Cookiecutter](https://github.com/audreyr/cookiecutter) & [cookiecutter-pypackage](https://github.com/audreyr/cookiecutter-pypackage).
- [ ] Add CI.
- [ ] Add badges for pypi version, build and docs status. (And more?)
- [ ] Use http://editorconfig.org
- [ ] Add AUTHORS
- [ ] Add CONTRIBUTING
- [ ] Add Makefile
- [ ] Add requirements.txt as well as Pipfiles (stick with Pipenv or switch back to pip-tools?)
- [ ] Add setup.cfg
- [ ] Run tests with tox if haven't done so yet
